[filename, pathname, filterindex] = uigetfile( ...
       {'*.pdf*',  'PDF files'}, ...
        'Pick a file', ...
        'MultiSelect', 'on');
    
fullfiles = fullfile(pathname,filename);
append_pdfs('test.pdf', fullfiles{:});