import block_model.classifiers.*;

classifiers = ...
     {
        {@adj_classifier,'adj'},...
        {@nb_classifier, 'nb'},...
        {@lap_classifier, 'lap'},...
        {@sym_norm_lap_classifier,'norm lap'},...
        {@adj_classifier, 'adj thresholding','use_kmeans',0},...
        {@nb_classifier, 'nb thresholding','use_kmeans',0},...
        {@lap_classifier, 'lap thresholding','use_kmeans',0},...
        {@sym_norm_lap_classifier, 'norm lap thresholding','use_kmeans',0}...
        {@sym_norm_adj_classifier,'cocktail','use_kmeans',0
     };

%   {@sym_norm_lap_classifier, 'normlap'}, ...
%     {@randwalk_classifier, 'randwalk'}, ...
%     {@pow_adj_classifier, 'adj (clean 1)','clean_c',1,'pow_c',0}, ...
%     {@pow_randwalk_classifier, 'randwalk (clean 0.5) (pow 0)', 'clean_c',0.5,'pow_c',0},...
%     {@pow_randwalk_classifier, 'randwalk (clean 0.5) (pow 0.15)', 'clean_c',0.5,'pow_c',0.15},...
%     {@pow_randwalk_classifier, 'randwalk (clean 0.5) (pow 0.2)','clean_c',0.5,'pow_c',0.2}, ...
%     {@pow_randwalk_classifier, 'randwalk (clean 0.5) (pow 0.3)','clean_c',0.5,'pow_c',0.3}, ...
%     {@pow_randwalk_classifier, 'randwalk (clean 0.5) (pow 0.5)','clean_c',0.5,'pow_c',0.5}, ...
%     {@pow_randwalk_classifier, 'randwalk (no clean) (pow 0.05)','no_clean',true,'pow_c',0.05}, ...
%     {@pow_randwalk_classifier, 'randwalk (no clean) (pow 0.1)','no_clean',true,'pow_c',0.1}, ...
%     {@pow_randwalk_classifier, 'randwalk (no clean) (pow 0.15)','no_clean',true,'pow_c',0.15}, ...
%     {@pow_randwalk_classifier, 'randwalk (no clean) (pow 0.2)','no_clean',true,'pow_c',0.2}, ...
%     {@pow_randwalk_classifier, 'randwalk (no clean) (pow 0.3)','no_clean',true,'pow_c',0.3}, ...
%         {@pow_adj_classifier, 'pow (adj) none 0','no_clean',true,'pow_c',0},... 
%     {@pow_adj_classifier, 'pow (adj) none 0.15','no_clean',true,'pow_c',0.15},... 
%       {@pow_adj_classifier, 'pow (adj) none 0.3','no_clean',true,'pow_c',0.3}, ...
%       {@pow_adj_classifier, 'pow (adj) none 0.5','no_clean',true,'pow_c',0.5}, ...
%       {@pow_adj_classifier, 'pow (adj) none 1','no_clean',true,'pow_c',1}, ... %   {@pow_adj_classifier, 'pow (adj) none 2','no_clean',true,'pow_c',2}, ...
%       ...
%     {@lap_classifier, 'lap'},...
%     {@adj_classifier,'adj'}


% classifiers = {{@nb_classifier, 'nb'}};
% {@pow_nb_classifier, 'nb (clean 1)','clean_c',1,'pow_c',0}, ...
% %         {@nb_classifier, 'nb'}, ...
%  classifiers = ...
%          {
% %         {@sdp_classifier, 'sdp'}, ...
%         {@adj_classifier, 'adj'}, ...
%          {@lap_classifier, 'lap'}, ...
%         {@sym_norm_lap_classifier, 'normlap'}, ...
%         {@pow_adj_classifier, 'graphpow (adj)'}, ...
%      {@pow_adj_classifier, 'graphpow (adj) 2 0.15', 'clean_c',2,'pow_c',0.15},... 
%      {@pow_adj_classifier, 'graphpow (adj) 2 0.3','clean_c',2,'pow_c',0.3}, ...
%      {@pow_adj_classifier, 'graphpow (adj) 2 0.5', 'clean_c',2,'pow_c',0.5}, ...
%      {@pow_adj_classifier, 'graphpow (adj) 2 1','clean_c',2,'pow_c',1}, ...
%      {@pow_adj_classifier, 'graphpow (adj) 2 2','clean_c',2,'pow_c',2}, ...
%      ...
%      {@pow_lap_classifier, 'graphpow (lap) 2 0.15', 'clean_c',2,'pow_c',0.15},... 
%      {@pow_lap_classifier, 'graphpow (lap) 2 0.3','clean_c',2,'pow_c',0.3}, ...
%      {@pow_lap_classifier, 'graphpow (lap) 2 0.5', 'clean_c',2,'pow_c',0.5}, ...
%      {@pow_lap_classifier, 'graphpow (lap) 2 1','clean_c',2,'pow_c',1}, ...
%      {@pow_lap_classifier, 'graphpow (lap) 2 2','clean_c',2,'pow_c',2}, ...
%      ...
%      {@pow_sym_norm_lap_classifier, 'graphpow (norm lap) 2 0.15', 'clean_c',2,'pow_c',0.15},... 
%      {@pow_sym_norm_lap_classifier, 'graphpow (norm lap) 2 0.3','clean_c',2,'pow_c',0.3}, ...
%      {@pow_sym_norm_lap_classifier, 'graphpow (norm lap) 2 0.5', 'clean_c',2,'pow_c',0.5}, ...
%      {@pow_sym_norm_lap_classifier, 'graphpow (norm lap) 2 1','clean_c',2,'pow_c',1}, ...
%      {@pow_sym_norm_lap_classifier, 'graphpow (norm lap) 2 2','clean_c',2,'pow_c',2}, ...
%      {@pow_sym_norm_lap_classifier, 'normlap', 'no_clean',true,'pow_c',0},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (pow 0.15)', 'no_clean',true,'pow_c',0.15},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (pow 0.3)', 'no_clean',true,'pow_c',0.3},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (pow 0.5)', 'no_clean',true,'pow_c',0.5},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (pow 1)', 'no_clean',true,'pow_c',1},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (pow 2)', 'no_clean',true,'pow_c',2},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (pow 3)', 'no_clean',true,'pow_c',3},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (pow 4)', 'no_clean',true,'pow_c',4},... 
%      ...
%      {@pow_randwalk_classifier, 'graphpow (randwalk) 2 0.15', 'clean_c',2,'pow_c',0.15},... 
%      {@pow_randwalk_classifier, 'graphpow (randwalk) 2 0.3','clean_c',2,'pow_c',0.3}, ...
%      {@pow_randwalk_classifier, 'graphpow (randwalk) 2 0.5', 'clean_c',2,'pow_c',0.5}, ...
%      {@pow_randwalk_classifier, 'graphpow (randwalk) 2 1','clean_c',2,'pow_c',1}, ...
%      {@pow_randwalk_classifier, 'graphpow (randwalk) 2 2','clean_c',2,'pow_c',2}, ...
%      ...
%      {@pow_adj_classifier, 'pow (adj) none 0','no_clean',true,'pow_c',0},... 
%      {@pow_adj_classifier, 'pow (adj) none 0.15','no_clean',true,'pow_c',0.15},... 
%      {@pow_adj_classifier, 'pow (adj) none 0.3','no_clean',true,'pow_c',0.3}, ...
%      {@pow_adj_classifier, 'pow (adj) none 0.5','no_clean',true,'pow_c',0.5}, ...
%      {@pow_adj_classifier, 'pow (adj) none 1','no_clean',true,'pow_c',1}, ... %   {@pow_adj_classifier, 'pow (adj) none 2','no_clean',true,'pow_c',2}, ...
%       ...
%      {@pow_lap_classifier, 'pow (lap) none 0', 'no_clean',true,'pow_c',0},... 
%      {@pow_lap_classifier, 'pow (lap) none 0.15','no_clean',true,'pow_c',0.15},... 
%      {@pow_lap_classifier, 'pow (lap) none 0.3','no_clean',true,'pow_c',0.3}, ...
%      {@pow_lap_classifier, 'pow (lap) none 0.5','no_clean',true,'pow_c',0.5}, ...
%      {@pow_lap_classifier, 'pow (lap) none 1','no_clean',true,'pow_c',1}, ... %   {@pow_lap_classifier, 'pow (lap) none 2','no_clean',true,'pow_c',2}, ...
%      {@pow_lap_classifier, 'lap (no clean)', 'no_clean',true,'pow_c',0},... 
%      {@pow_lap_classifier, 'lap (clean 1)','clean_c',1,'pow_c',0},... 
%      {@pow_lap_classifier, 'lap (clean 2)','clean_c',2,'pow_c',0},... 
%      {@pow_lap_classifier, 'lap (clean 3)','clean_c',3,'pow_c',0},...
%      ...
%     {@pow_nb_classifier, 'nb (no clean)', 'no_clean',true,'pow_c',0},... 
%     {@pow_nb_classifier, 'nb (clean 1)','clean_c',1,'pow_c',0},... 
%      {@pow_nb_classifier, 'nb (clean 2)','clean_c',2,'pow_c',0},... 
%      {@pow_nb_classifier, 'nb (clean 3)','clean_c',3,'pow_c',0},...
%         {@pow_sym_norm_adj_classifier, 'normadj (no clean, pow 0.15)','no_clean',true,'pow_c',0.15},...
%         {@pow_sym_norm_adj_classifier, 'normadj (1 clean, pow 0.15)','clean_c',1,'pow_c',0.15},...
%         {@pow_sym_norm_adj_classifier, 'normadj (1 clean, no pow)','clean_c',1,'pow_c',0},...
%      ...
%      {@pow_sym_norm_lap_classifier, 'normlap (no clean)', 'no_clean',true,'pow_c',0},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (clean 1)','clean_c',1,'pow_c',0},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (clean 2)','clean_c',2,'pow_c',0},... 
%      {@pow_sym_norm_lap_classifier, 'normlap (clean 3)','clean_c',3,'pow_c',0},... 
%          };
%     
%      {@pow_nb_classifier, 'graphpow (nb) 2 0.15', 'clean_c',2,'pow_c',0.15},... 
%      {@pow_nb_classifier, 'graphpow (nb) 2 0.3','clean_c',2,'pow_c',0.3}, ...
%      {@pow_nb_classifier, 'graphpow (nb) 2 0.5', 'clean_c',2,'pow_c',0.5}, ...
%      {@pow_nb_classifier, 'graphpow (nb) 2 1','clean_c',2,'pow_c',1}, ... % {@pow_nb_classifier, 'graphpow (nb) 2 2','clean_c',2,'pow_c',2}, ...


realdatas = {...
    {@read_polblogs_graph,'polblogs','k',2},...
    {@read_twitter_graph,'twitter','k',2}
   };
agree_table = table({},{},{},{});
agree_table.Properties.VariableNames = {'data_set','classifier','agreement','time_elapsed'};

for datai = 1:length(realdatas)
    data_cell = realdatas{datai};
    data_load = data_cell{1};
    data_name = data_cell{2};
    data_k = data_cell{4};
    
    [community,A] = data_load(data_k);
    
    for classi = 1:length(classifiers)
        class_cell = classifiers{classi};
        class_func = class_cell{1};
        class_name = class_cell{2}
        
        tic
        class_guess = class_func(A,data_cell{3:end},class_cell{3:end});
        time_elapsed = toc;
        agreement = get_real_data_agreement(community,class_guess,data_cell{3:end})
        agree_table = [agree_table; {data_name, class_name, agreement, time_elapsed}]; %#ok<AGROW>
    end
end
agree_table
        